export const SET_USERNAME = 'SET_USERNAME';
export const SET_CONNECTED = 'SET_CONNECTED';
export const SET_CONNECTED_USERS = 'SET_CONNECTED_USERS';
export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST';
export const ADD_MESSAGE = 'ADD_MESSAGE';
